name: Manual Workflow Dispatch

on:
  workflow_dispatch:  # This triggers the workflow manually

jobs:
  test_curl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test curl command
        run: |
          namee = "lala/lolipop"
          packageName=$(basename $namee)
          # The curl command should print the value of the packageName variable
        #   response=$(curl -s -X POST \
  
        #   -H "Accept: application/vnd.github.v3+json" \
        #     -d '{
        #       "title": "[Release $packageName ${{ steps.increment_patch_version.outputs.CURRENT_VERSION }}] Prepare for next dev cycle",
        #       "body": "",
        #       "head": "'"$HEAD_BRANCH"'",
        #       "base": "'"$BASE_BRANCH"'"
        #     }')

        #   echo "$response"